// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroDeTickets.Data.Entidades;

#nullable disable

namespace RegistroDeTickets.Data.Migrations
{
    [DbContext(typeof(RegistroDeTicketsPw3Context))]
    partial class RegistroDeTicketsPw3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Admin");

                    b.ToTable("Administrador", (string)null);
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.ReporteTecnico", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.HasKey("IdReporte");

                    b.HasIndex("IdTicket");

                    b.ToTable("ReporteTecnico", (string)null);
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tecnico", (string)null);
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("Id_cliente");

                    b.Property<int?>("IdTecnico")
                        .HasColumnType("int")
                        .HasColumnName("Id_tecnico");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTecnico");

                    b.HasIndex("PrioridadId");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.TicketEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nombre" }, "UQ_TicketEstado_Nombre")
                        .IsUnique();

                    b.ToTable("TicketEstado", (string)null);
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.TicketPrioridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nombre" }, "UQ_TicketPrioridad_Nombre")
                        .IsUnique();

                    b.ToTable("TicketPrioridad", (string)null);
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenHashRecuperacion")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("TokenHashRecuperacionExpiracion")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_usuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Administrador", b =>
                {
                    b.HasOne("RegistroDeTickets.Data.Entidades.Usuario", "IdNavigation")
                        .WithOne("Administrador")
                        .HasForeignKey("RegistroDeTickets.Data.Entidades.Administrador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Admin_Usuario");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Cliente", b =>
                {
                    b.HasOne("RegistroDeTickets.Data.Entidades.Usuario", "IdNavigation")
                        .WithOne("Cliente")
                        .HasForeignKey("RegistroDeTickets.Data.Entidades.Cliente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Usuario");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.ReporteTecnico", b =>
                {
                    b.HasOne("RegistroDeTickets.Data.Entidades.Ticket", "IdTicketNavigation")
                        .WithMany("ReporteTecnicos")
                        .HasForeignKey("IdTicket")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket");

                    b.Navigation("IdTicketNavigation");
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Tecnico", b =>
                {
                    b.HasOne("RegistroDeTickets.Data.Entidades.Usuario", "IdNavigation")
                        .WithOne("Tecnico")
                        .HasForeignKey("RegistroDeTickets.Data.Entidades.Tecnico", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tecnico_Usuario");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Ticket", b =>
                {
                    b.HasOne("RegistroDeTickets.Data.Entidades.TicketEstado", "Estado")
                        .WithMany("Tickets")
                        .HasForeignKey("EstadoId")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Estado");

                    b.HasOne("RegistroDeTickets.Data.Entidades.Cliente", "IdClienteNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Cliente");

                    b.HasOne("RegistroDeTickets.Data.Entidades.Tecnico", "IdTecnicoNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("IdTecnico")
                        .HasConstraintName("FK_Ticket_Tecnico");

                    b.HasOne("RegistroDeTickets.Data.Entidades.TicketPrioridad", "Prioridad")
                        .WithMany("Tickets")
                        .HasForeignKey("PrioridadId")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Prioridad");

                    b.Navigation("Estado");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdTecnicoNavigation");

                    b.Navigation("Prioridad");
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Cliente", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Tecnico", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Ticket", b =>
                {
                    b.Navigation("ReporteTecnicos");
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.TicketEstado", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.TicketPrioridad", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("RegistroDeTickets.Data.Entidades.Usuario", b =>
                {
                    b.Navigation("Administrador");

                    b.Navigation("Cliente");

                    b.Navigation("Tecnico");
                });
#pragma warning restore 612, 618
        }
    }
}
